# Generated by Django 5.1.7 on 2025-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sekvens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sekvens", models.TextField()),
                ("n_param", models.IntegerField()),
                ("a_param", models.TextField()),
                ("family", models.IntegerField(blank=True, null=True)),
                ("biggest", models.IntegerField(blank=True, null=True)),
                ("sorted_sekvens", models.TextField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sekvens", "n_param", "a_param"),
                        name="unique_sekvens_params",
                    )
                ],
            },
        ),
    ]
